# Generated by Django 3.2.25 on 2025-01-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id_artista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_nascimento', models.DateField()),
                ('data_falecimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('breve_descricao', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('genero', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classico', 'Clássica'), ('hip_hop', 'Hip Hop'), ('eletronica', 'Eletrônica')], max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_de_lancamento', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='albums/')),
                ('artista', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
            ],
        ),
    ]
