# Generated by Django 3.2.25 on 2025-01-20 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20250120_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
