# Generated by Django 3.2.25 on 2025-01-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_album_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilutilizador',
            name='albuns_favoritos',
        ),
        migrations.RemoveField(
            model_name='perfilutilizador',
            name='artistas_favoritos',
        ),
        migrations.RemoveField(
            model_name='perfilutilizador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='album',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='FavoriteAlbum',
        ),
        migrations.DeleteModel(
            name='PerfilUtilizador',
        ),
    ]
