# Generated by Django 3.2.25 on 2025-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250120_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
    ]
