# Generated by Django 3.2.25 on 2025-02-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carrinho_carrinhoalbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhoalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhoalbum', to='core.album'),
        ),
    ]
