# Generated by Django 3.2.25 on 2025-02-06 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_carrinhoalbum_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('quando_adicionado', models.DateTimeField(auto_now_add=True)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrinhoalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='carrinhoalbum',
            name='carrinho',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='CarrinhoAlbum',
        ),
    ]
