# Generated by Django 3.2.25 on 2025-05-02 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20250207_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='Artista_favorito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
