# Generated by Django 3.2.25 on 2025-05-21 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20250502_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='artista_favorito', to=settings.AUTH_USER_MODEL),
        ),
    ]
