# Generated by Django 3.2.25 on 2025-05-28 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='album_favorito', to=settings.AUTH_USER_MODEL),
        ),
    ]
