# Generated by Django 4.2.5 on 2025-06-01 15:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_album_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_perfil'),
        ),
    ]
