# Generated by Django 3.2.25 on 2025-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20250526_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
