# Generated by Django 3.2.25 on 2025-05-26 23:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0007_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('room', 'invited_user', 'accepted')},
        ),
    ]
