# Generated by Django 3.2.25 on 2025-06-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=23),
        ),
    ]
